version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    # Bug detection
    - govet          # Reports suspicious constructs
    - ineffassign    # Detects unused variable assignments
    - staticcheck    # Comprehensive static analysis
    - unused         # Checks for unused code
    - errcheck       # Check for unchecked errors
    - bodyclose      # Check HTTP response bodies are closed
    - nilerr         # Check for nil error returns
    - copyloopvar    # Check for loop variable capture issues
    
    # Code quality
    - misspell       # Check for spelling errors
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Detect unused function parameters
    - prealloc       # Find slice declarations that could be pre-allocated
    
    # Security
    - gosec          # Security checks

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      excludes:
        - G104  # Audit errors not checked (too noisy)
        - G304  # File path provided as taint input (needed for file operations)
        - G301  # Directory permissions (we use 0755 intentionally)
        - G302  # File permissions (we use 0644 intentionally for config files)
        - G306  # WriteFile permissions (we use 0644 intentionally)
        - G112  # Slowloris (proxy server doesn't need ReadHeaderTimeout)
        - G101  # Hardcoded credentials (false positive on env var names)
        - G115  # Integer overflow (too strict for our use case)
        - G404  # Weak random (chaos testing intentionally uses math/rand)
        - G204  # Subprocess with variable (benchmark runner needs this)
    staticcheck:
      checks:
        - all
        - -SA1019  # Deprecated usage (too strict for some stdlib)

  exclusions:
    rules:
      # Test files have looser requirements
      - path: "_test\\.go"
        linters:
          - errcheck
          - gosec
          - ineffassign
          - unparam
          - prealloc
      # Examples and benchmarks
      - path: "^examples/"
        linters:
          - errcheck
          - ineffassign
      - path: "^benchmarks/"
        linters:
          - errcheck
          - ineffassign
          - gosec
      - path: "^tests/"
        linters:
          - errcheck
          - gosec
          - unparam
          - prealloc
