version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - ineffassign
      - path: "^examples/"
        linters:
          - ineffassign
      - path: "^benchmarks/"
        linters:
          - ineffassign
      - path: "^tests/"
        linters:
          - ineffassign
